name: Jenkins Security Scan
on:
  push:
    branches:
      - $default-branch
  pull_request:
    types: [ opened, synchronize, reopened ]
  workflow_dispatch:

jobs:
  security-scan:
    uses: jenkins-infra/jenkins-security-scan/.github/workflows/jenkins-security-scan.yaml@main
    with:
      java-cache: '' # Optionally enable use of a build dependency cache. Specify 'maven' or 'gradle' as appropriate.
      java-version: 8 # What version of Java to set up for the build.
