name: Release Drafter
on:
  workflow_call:

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5.19.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
